### PR TITLE
GD-115: Fix Debug tests gets stuck when using `--verbose`

### PR DESCRIPTION
**Pull request by MikeSchulze**
# What
see https://github.com/MikeSchulze/gdUnit4Net/issues/115 The debugger was on hold because of printing system outs and the process has not start reading stdout and stderr

# What
- Moved the attach debugger after begin reading stdout and stderr
- fixed local nuget config to build against local nuget packages

### CODE REVIEW

**Comment by MikeSchulze** [comment]
@van800 can you please check the debug works on rider?
The version is not released yet, you need to check out the master and run the example project and edit the nuget.config inside the project to load the latest package versions.

**Comment by van800** [comment]
@MikeSchulze I have tried that, I have double-checked to use locally compiled nugets. However, it doesn't work. I believe it is still a problem [on our side](https://youtrack.jetbrains.com/issue/RSRP-496314/Rider-Support-debugging-in-gdUnit4Net). 

```
Last runner error: TestRunner: JetBrains.ReSharper.TestRunner.Adapters.VsTest.Executor Could not attach debugger System.AggregateException: One or more errors occurred. (Specified method is not supported., reason: System.NotSupportedException: Specified method is not supported.
   at JetBrains.Rider.Backend.Features.UnitTesting.RiderUnitTestDebugHost.AttachToProcess(IUnitTestRun run, String remoteMachine, Int32 processId)
   at JetBrains.ReSharper.UnitTestFramework.Execution.Hosting.DebugHostController.AttachToProcess(Int32 processId, IUnitTestRun run, ILogger logger)
   at JetBrains.ReSharper.UnitTestFramework.Execution.Launch.UnitTestLaunch.HostControllerWithLogging.AttachToProcess(Int32 processId, IUnitTestRun run, ILogger logger)
   at JetBrains.ReSharper.UnitTestFramework.Execution.Launch.UnitTestLaunch.HostControllerWithExtensions.AttachToProcess(Int32 processId, IUnitTestRun run, ILogger logger)
   at JetBrains.ReSharper.UnitTestFramework.Execution.TestRunner.DefaultTestRunnerHost.TestExecutionMessageHandler.Execute(AttachToProcessRequest message)
   at JetBrains.ReSharper.UnitTestFramework.Execution.TestRunner.Activation.ServerEndpoint.<>c__DisplayClass7_1.<<TryRegisterAsyncHandler>b__0>d.MoveNext()
   
   ```

**Comment by MikeSchulze** [comment]
> @MikeSchulze I have tried that, I have double-checked to use locally compiled nugets. However, it doesn't work. I believe it is still a problem [on our side](https://youtrack.jetbrains.com/issue/RSRP-496314/Rider-Support-debugging-in-gdUnit4Net).
> 
> ```
> Last runner error: TestRunner: JetBrains.ReSharper.TestRunner.Adapters.VsTest.Executor Could not attach debugger System.AggregateException: One or more errors occurred. (Specified method is not supported., reason: System.NotSupportedException: Specified method is not supported.
>    at JetBrains.Rider.Backend.Features.UnitTesting.RiderUnitTestDebugHost.AttachToProcess(IUnitTestRun run, String remoteMachine, Int32 processId)
>    at JetBrains.ReSharper.UnitTestFramework.Execution.Hosting.DebugHostController.AttachToProcess(Int32 processId, IUnitTestRun run, ILogger logger)
>    at JetBrains.ReSharper.UnitTestFramework.Execution.Launch.UnitTestLaunch.HostControllerWithLogging.AttachToProcess(Int32 processId, IUnitTestRun run, ILogger logger)
>    at JetBrains.ReSharper.UnitTestFramework.Execution.Launch.UnitTestLaunch.HostControllerWithExtensions.AttachToProcess(Int32 processId, IUnitTestRun run, ILogger logger)
>    at JetBrains.ReSharper.UnitTestFramework.Execution.TestRunner.DefaultTestRunnerHost.TestExecutionMessageHandler.Execute(AttachToProcessRequest message)
>    at JetBrains.ReSharper.UnitTestFramework.Execution.TestRunner.Activation.ServerEndpoint.<>c__DisplayClass7_1.<<TryRegisterAsyncHandler>b__0>d.MoveNext()
>    
> ```

I know the issue of `AttachDebuggerToProcess` not implemented, that's a JetBrains problem.
For me, it is from interesting that the workaround you proposed is working as before.
Unfortunately, I can't test this myself because I don't have a Rider license.

**Comment by van800** [comment]
Ah, I forgot that workaround. I will test tomorrow.

**Comment by van800** [comment]
The workaround with `while (!Debugger.IsAttached)` still works as before.

**Comment by MikeSchulze** [comment]
> The workaround with `while (!Debugger.IsAttached)` still works as before.

thanks for your feedback 👍

**Comment by van800** [comment]
@MikeSchulze Regarding a Rider license, we'd be happy to provide one for you. I have wrote to your email stated in the github profile, from my jetbrains address.

**Comment by MikeSchulze** [comment]
> @MikeSchulze Regarding a Rider license, we'd be happy to provide one for you. I have wrote to your email stated in the github profile, from my jetbrains address.

Thank you for this message, I have an answer and yes, I am very interested in the license ;)

**Pull request merged**
