### PR TITLE
GD-124: Use `LaunchProcessWithDebuggerAttached` instead of `AttachDebuggerIfNeed` for Rider 2024.2

### PR DESCRIPTION
**Pull request by MikeSchulze**

### CODE REVIEW

**Comment by MikeSchulze** [comment]
Hi @van800 I got it running under Windows and macOS, so far so good.

On Windows, the debugger starts and finish successfully.
On macOS, it stuck at the end and the debug process is never closed and needs to be manually closed.

Looks like the `EnableShutdownAfterTestRun` flag has no effect. 

If you have time, it would be nice to take a look at this, maybe you have an idea what goes wrong here.

**Comment by van800** [comment]
Hi @MikeSchulze ! That is great news.
I have tried on MacOSX with Godot 4.2.2 and 4.3-beta2. Debugging and closing after the run - all is as expected.

On 4.2.2 
Debug process started /Applications/Godot422_mono.app/Contents/MacOS/Godot /Users/ivan.shakhov/Work/gdUnit4Net/test -d --path . res://gdunit4_testadapter/TestAdapterRunner.tscn --testadapter --configfile="/Users/ivan.shakhov/Work/gdUnit4Net/test/GdUnitRunner_0bf5b342-19f7-4d17-956f-642c4c80fb35.cfg" 
Process exited: HasExited: True True Microsoft.Win32.SafeHandles.SafeProcessHandle
Process exited: HasExited: True False

On 4.3-beta2
Debug process started /Applications/Godot_mono_v4.3-beta2.app/Contents/MacOS/Godot /Users/ivan.shakhov/Work/gdUnit4Net/test -d --path . res://gdunit4_testadapter/TestAdapterRunner.tscn --testadapter --configfile="/Users/ivan.shakhov/Work/gdUnit4Net/test/GdUnitRunner_8c207503-6c84-40f4-9340-a6635107c831.cfg" 
Process exited: HasExited: True True Microsoft.Win32.SafeHandles.SafeProcessHandle
Process exited: HasExited: True False

Please let me know, if if should check anything else.
If the problem persists, please report (after your run is not finished) with Help->Report a Bug, agree to attach logs, I will ask the UnitTesting folks to look at it.

**Comment by MikeSchulze** [comment]
> Hi @MikeSchulze ! That is great news. I have tried on MacOSX with Godot 4.2.2 and 4.3-beta2. Debugging and closing after the run - all is as expected.
> 
> On 4.2.2 Debug process started /Applications/Godot422_mono.app/Contents/MacOS/Godot /Users/ivan.shakhov/Work/gdUnit4Net/test -d --path . res://gdunit4_testadapter/TestAdapterRunner.tscn --testadapter --configfile="/Users/ivan.shakhov/Work/gdUnit4Net/test/GdUnitRunner_0bf5b342-19f7-4d17-956f-642c4c80fb35.cfg" Process exited: HasExited: True True Microsoft.Win32.SafeHandles.SafeProcessHandle Process exited: HasExited: True False
> 
> On 4.3-beta2 Debug process started /Applications/Godot_mono_v4.3-beta2.app/Contents/MacOS/Godot /Users/ivan.shakhov/Work/gdUnit4Net/test -d --path . res://gdunit4_testadapter/TestAdapterRunner.tscn --testadapter --configfile="/Users/ivan.shakhov/Work/gdUnit4Net/test/GdUnitRunner_8c207503-6c84-40f4-9340-a6635107c831.cfg" Process exited: HasExited: True True Microsoft.Win32.SafeHandles.SafeProcessHandle Process exited: HasExited: True False
> 
> Please let me know, if I should check anything else. If the problem persists, please report (after your run is not finished) with Help->Report a Bug, agree to attach logs, I will ask the UnitTesting folks to look at it.

ok that's strange I get `exited: HasExited: False False` and the debuger is still running on macOS with Godot4.2.2

**Comment by dvankley** [comment]
@MikeSchulze Thanks for your work on this! I'm very excited to try out the streamlined debug functionality in Rider. When will the next release go out?

**Comment by MikeSchulze** [comment]
> @MikeSchulze Thanks for your work on this! I'm very excited to try out the streamlined debug functionality in Rider. When will the next release go out?

Released ;)

**Comment by dvankley** [comment]
Thanks! Works great. Massive improvement in my workflow.

**Comment by MikeSchulze** [comment]
> Thanks! Works great. Massive improvement in my workflow.

Nice to hear that it is well received

**Comment by StefanH-AT** [comment]
AWESOME! Thank you! This is such a core part of my workflow. I was really excited to discover this great unit testing framework for godot only to find out it didn't support debugging, which was a massive letdown. So really amazing that is is finally working!!

**Pull request merged**
